api_platform:
    title: 'API Platform Starter'
    # The description of the API.
    description: 'Api demi-scratch - entities: [User] - Basic auth system [username,password]'

    # The version of the API.
    version: '0.1.1'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
          apiKey:
            name: Authorization
            type: header